apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denier
  namespace: default
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denier
  namespace: default
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denier
  namespace: default
spec:
  match: destination.labels["app"] == "httpbin"
  actions:
  - handler: denier
    instances: [ denier ]